language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"

before_install:
- composer self-update
- composer clear-cache
- composer require "fxp/composer-asset-plugin:^1.4"
- mysql -e 'CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'

install:
- travis_retry composer self-update
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- travis_retry composer install $DEFAULT_COMPOSER_FLAGS

script:
- ./vendor/bin/codecept run --debug

services:
  - mysql