language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

before_install:
- composer self-update
- composer clear-cache
- mysql -e 'CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('123456') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo service mysql restart


install:
- composer install --ignore-platform-reqs

before_script:

script:
- ./vendor/bin/codecept run

services:
  - mysql